//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Round3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.RentaDevolucion = new HashSet<RentaDevolucion>();
        }
    
        public int idEmpleado { get; set; }
        public string nombreEmpleado { get; set; }
        public string tandaLabor { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public string cedulaEmpleado { get; set; }
        public bool estadoEmpleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentaDevolucion> RentaDevolucion { get; set; }
    }
}
