//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Round3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.RentaDevolucion = new HashSet<RentaDevolucion>();
        }
    
        public int idEquipo { get; set; }
        public string nombreEquipo { get; set; }
        public string descripcionEquipo { get; set; }
        public string serial { get; set; }
        public int idTE { get; set; }
        public int idModelo { get; set; }
        public int idTC { get; set; }
        public bool estadoEquipo { get; set; }
    
        public virtual Modelo Modelo { get; set; }
        public virtual TecnologiaConexion TecnologiaConexion { get; set; }
        public virtual TipoEquipo TipoEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentaDevolucion> RentaDevolucion { get; set; }
    }
}
