//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Round3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.RentaDevolucion = new HashSet<RentaDevolucion>();
        }
    
        public int idUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public int noCarnet { get; set; }
        public int idTipoU { get; set; }
        public int idTipoP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentaDevolucion> RentaDevolucion { get; set; }
        public virtual TipoPersona TipoPersona { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
